---
# tasks file for Atom

- name: Log object names
  debug:
    msg: "Applying {{ item.object.metadata.name }}"
  loop: "{{ objects }}"
  loop_control:
    label: "{{ item.object.metadata.name }}"

- name: Apply objects
  k8s:
    resource_definition: "{{ objects | map(attribute='object') | list }}"
    validate:
      fail_on_error: true
      strict: true
